jdih/urls.py
from django.urls import path

from jdih import views

app_name = "jdih"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<uuid:peraturan_id>/", views.detail, name="detail"),
    path("detail/<uuid:peraturan_id>/unduh/", views.unduh, name="unduh"),
    path("daftar-peraturan/", views.daftar_peraturan, name="daftar_peraturan"),
    path("cari/", views.cari, name="cari"),
]

jdih_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


def errtest(request):
    raise Exception("This is a test error.")


urlpatterns = [
    path("admin-jdih/", admin.site.urls),
    # path("errtest/", errtest, name="errtest"),
    path("", include("jdih.urls")),
    # debug toolbar
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jdih/models.py
import datetime
import uuid

from django.contrib.postgres.search import SearchVectorField
from django.db import models
from django.utils.text import slugify

from .custom_fields import ContentTypeRestrictedFileField


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Peraturan(TimeStampedModel):
    """Model repr peraturan (dokumen hukum)."""

    BAHASA_CHOICES = (
        ("indonesia", "Bahasa Indonesia"),
        ("inggris", "Bahasa Inggris"),
    )

    BERLAKU = "berlaku"
    TIDAK_BERLAKU = "tidak_berlaku"
    STATUS_CHOICES = ((BERLAKU, "Berlaku"), (TIDAK_BERLAKU, "Tidak Berlaku"))

    DICABUT = "dicabut"
    DICABUT_SEBAGIAN = "dicabut_sebagian"
    DIUBAH = "diubah"
    DILENGKAPI = "dilengkapi"
    LAINNYA = "lainnya"
    ALASAN_TIDAK_BERLAKU_CHOICES = (
        (DICABUT, "Dicabut"),
        (DICABUT_SEBAGIAN, "Dicabut sebagian"),
        (DIUBAH, "Diubah"),
        (DILENGKAPI, "Dilengkapi"),
        (LAINNYA, "Lainnya"),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # kode: HK.01.07/MENKES/1134/2022 etc..
    ht_kode = "Misalnya: HK.01.07/MENKES/123/2024"
    kode = models.CharField(
        max_length=150, unique=True, verbose_name="kode peraturan", help_text=ht_kode
    )
    judul = models.CharField(
        max_length=300,
        help_text="Misalnya: Jam Kerja Pegawai di Lingkungan Kementerian Kesehatan Selama Bulan Ramadhan",
    )
    # kode + judul
    kode_judul = models.CharField(max_length=500, null=True, blank=True, editable=False)
    # bentuk: UUD, Tap MPR, fk
    bentuk = models.ForeignKey(
        "BentukPeraturan",
        related_name="peraturans",
        verbose_name="bentuk peraturan",
        on_delete=models.CASCADE,
    )
    nomor = models.IntegerField(blank=True, null=True)
    tahun = models.IntegerField(default=datetime.datetime.now().year)
    unit_eselon_1_pemrakarsa = models.CharField(
        verbose_name="eselon 1 pemrakarsa", max_length=150, blank=True, null=True
    )
    tempat_penetapan = models.CharField(max_length=100, blank=True, null=True)
    tanggal_penetapan = models.DateField(blank=True, null=True)
    tanggal_pengundangan = models.DateField(blank=True, null=True)
    tanggal_berlaku_efektif = models.DateField(blank=True, null=True)
    # lokasi dokumen fisik, contoh Biro Hukum
    lokasi = models.CharField(
        max_length=100, help_text="contoh: Biro Hukum", blank=True, null=True
    )
    # sumber: berita negara (BN) nomor sekian..
    sumber = models.CharField(
        max_length=100, help_text="contoh: BN nomor sekian", blank=True, null=True
    )
    bahasa = models.CharField(
        max_length=20, choices=BAHASA_CHOICES, blank=True, null=True
    )
    # bid_huk: Hukum Keuangan Negara
    bidang_hukum = models.CharField(
        max_length=100, help_text="contoh: Hukum Keuangan Negara", blank=True, null=True
    )
    # subyek (tag) m2m
    subyek = models.ManyToManyField(
        "Subyek", blank=True, verbose_name="subyek atau tag"
    )
    kategori = models.ManyToManyField("Kategori", blank=True)
    # tema: BMN, Covid-19, etc. m2m
    tema = models.ManyToManyField("Tema", blank=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=BERLAKU)
    alasan_tidak_berlaku = models.CharField(
        max_length=50, choices=ALASAN_TIDAK_BERLAKU_CHOICES, null=True, blank=True
    )

    mencabuts = models.ManyToManyField(
        to="self",
        symmetrical=False,
        blank=True,
        related_name="pencabuts",
        verbose_name="mencabut",
    )
    mencabut_sebagians = models.ManyToManyField(
        to="self",
        symmetrical=False,
        blank=True,
        related_name="pencabut_sebagians",
        verbose_name="mencabut sebagian",
    )
    mengubahs = models.ManyToManyField(
        to="self",
        symmetrical=False,
        blank=True,
        related_name="pengubahs",
        verbose_name="mengubah/melengkapi",
    )
    melengkapis = models.ManyToManyField(
        to="self",
        symmetrical=False,
        blank=True,
        related_name="pelengkaps",
        verbose_name="melengkapi",
    )

    # Teks hasil ektraksi PDF peraturan
    teks = models.TextField(blank=True, null=True, editable=False)
    teks_vektor = SearchVectorField(blank=True, null=True, editable=False)
    last_teks_ingestion = models.DateTimeField(blank=True, null=True, editable=False)
    teks_ingestion_error_message = models.TextField(
        blank=True, null=True, editable=False
    )
    file_dokumen = ContentTypeRestrictedFileField(
        upload_to="dokumen_hukum/",
        blank=True,
        null=True,
        content_types=["application/pdf"],
        max_upload_size=30 * 1024 * 1024,
    )
    jumlah_lihat = models.IntegerField(default=0, editable=False)
    jumlah_unduh = models.IntegerField(default=0, editable=False)

    class Meta:
        ordering = ("-created_at",)
        verbose_name_plural = "peraturan"
        indexes = [
            models.Index(fields=["kode_judul"]),
            # GinIndex(
            #     name="peraturan_gin_idx",
            #     fields=["teks", "judul", "kode"],
            # )
        ]

    def save(self, *args, **kwargs):
        self.kode_judul = f"{self.kode} {self.judul}"
        super().save(*args, **kwargs)

    def __str__(self):
        # if len(self.judul) > 20:
        #     return f"{self.kode} {str(self.judul)[:20]}"
        # else:
        #     return f"{self.kode} {self.judul}"
        return f"{self.kode} {self.judul}"


# class Cabut(TimeStampedModel):
#     pencabut = models.ForeignKey(
#         "Peraturan", on_delete=models.CASCADE, related_name="to_peraturans"
#     )
#     tercabut = models.ForeignKey(
#         "Peraturan",
#         on_delete=models.CASCADE,
#         related_name="from_peraturans",
#         verbose_name="peraturan tercabut",
#     )

#     def __str__(self):
#         return str(self.tercabut)

#     class Meta:
#         verbose_name = "Mencabut Peraturan"
#         verbose_name_plural = "Mencabut Peraturan"
#         ordering = ("updated_at",)
#         constraints = [
#             models.UniqueConstraint(
#                 name="%(app_label)s_%(class)s_unique_relationships",
#                 fields=["pencabut", "tercabut"],
#             ),
#             models.CheckConstraint(
#                 name="%(app_label)s_%(class)s_cegah_self_cabut",
#                 check=~models.Q(pencabut=models.F("tercabut")),
#             ),
#         ]


class BentukPeraturan(TimeStampedModel):
    """Model repr bentuk peraturan e.g. UUD, KMK"""

    nama_lengkap_bentuk = models.CharField(
        max_length=100,
        verbose_name="nama bentuk peraturan",
        help_text="contoh: Peraturan Presiden",
    )
    # slug untuk memastikan tidak ada nama yang sama
    slug = models.CharField(max_length=100, default="", editable=False, unique=True)
    singkatan_nama_bentuk = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        verbose_name="singkatan",
        help_text="contoh: PP",
    )
    # field bool utk menandai apakah dia tayang di home
    tayang = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.singkatan_nama_bentuk:
            new_string = ""
            words = self.nama_lengkap_bentuk.split()

            for word in words:
                new_string += word[0].upper()
            self.singkatan_nama_bentuk = new_string
        self.slug = slugify(self.nama_lengkap_bentuk)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.nama_lengkap_bentuk} ({self.singkatan_nama_bentuk})"

    class Meta:
        verbose_name_plural = "bentuk peraturan"


class Subyek(TimeStampedModel):
    """Model repr subyek (tag) peraturan/dokumen hukum."""

    judul = models.CharField(
        max_length=50, unique=True, help_text="judul subyek atau tag"
    )

    def save(self, *args, **kwargs):
        if self.judul:
            self.judul = self.judul.lower()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name_plural = "subyek"


class Kategori(TimeStampedModel):
    """Model repr kategori."""

    judul = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(default="", editable=False, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.judul)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name_plural = "kategori"


class Tema(TimeStampedModel):
    """Model repr tematik."""

    judul = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(default="", editable=False, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.judul)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name_plural = "tema"

jdih/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.text import slugify

from .models import BentukPeraturan, Kategori, Peraturan, Tema


class PeraturanForm(forms.ModelForm):
    # tidak perlu ada Meta karena
    # sejauh ini Form ini hanya untuk situs admin

    def clean_kode(self):
        kode = self.cleaned_data["kode"]
        duplicate_found = Peraturan.objects.filter(kode=kode).exists()
        if duplicate_found and self.instance.pk is None:
            raise ValidationError("Peraturan dengan kode yang sama sudah ada.")
        return kode


class BentukPeraturanForm(forms.ModelForm):
    # tidak perlu ada Meta karena
    # sejauh ini Form ini hanya untuk situs admin

    def clean_nama_lengkap_bentuk(self):
        nama_lengkap_bentuk = self.cleaned_data["nama_lengkap_bentuk"]
        slug = slugify(nama_lengkap_bentuk)
        duplicate_found = BentukPeraturan.objects.filter(slug=slug).exists()
        if duplicate_found and self.instance.pk is None:
            raise ValidationError("Bentuk peraturan ini sudah ada di sistem.")
        return nama_lengkap_bentuk


class KategoriForm(forms.ModelForm):
    # tidak perlu ada Meta karena
    # sejauh ini Form ini hanya untuk situs admin

    def clean_judul(self):
        judul = self.cleaned_data["judul"]
        slug = slugify(judul)
        duplicate_found = Kategori.objects.filter(slug=slug).exists()
        if duplicate_found and self.instance.pk is None:
            raise ValidationError("Kategori peraturan ini sudah ada di sistem.")
        return judul


class TemaForm(forms.ModelForm):
    # tidak perlu ada Meta karena
    # sejauh ini Form ini hanya untuk situs admin

    def clean(self):
        cleaned_data = super().clean()
        judul = cleaned_data.get("judul")
        slug = cleaned_data.get("slug")
        duplicate_found = (
            Tema.objects.filter(judul=judul).exists()
            or Tema.objects.filter(slug=slug).exists()
        )
        if duplicate_found and self.instance.pk is None:
            raise ValidationError("Tema peraturan ini sudah ada di sistem.")
        return cleaned_data

jdih/templates/jdih/_metatag.html
{% load static %}
<!-- Primary Meta Tags -->
<meta name="title" content="JDIH Kementerian Kesehatan" />
<meta name="description" content="Situs resmi Jaringan dan Informasi Hukum (JDIH) Kementerian Kesehatan Republik Indonesia" />

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website" />
<meta property="og:url" content="http://regulasi.bkpk.kemkes.go.id/" />
<meta property="og:title" content="JDIH Kementerian Kesehatan" />
<meta property="og:description" content="Situs resmi Jaringan dan Informasi Hukum (JDIH) Kementerian Kesehatan Republik Indonesia" />
<meta property="og:image" content="{% static 'jdih/img/bg-kemkes.png' %}" />

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image" />
<meta property="twitter:url" content="http://regulasi.bkpk.kemkes.go.id/" />
<meta property="twitter:title" content="JDIH Kementerian Kesehatan" />
<meta property="twitter:description" content="Situs resmi Jaringan dan Informasi Hukum (JDIH) Kementerian Kesehatan Republik Indonesia" />
<meta property="twitter:image" content="{% static 'jdih/img/bg-kemkes.png' %}" />

<!-- Meta Tags Generated with https://metatags.io -->

jdih/templates/jdih/daftar-peraturan.html
{% extends 'jdih/BASE.html' %}
{% load query_transform %}

{% block title_bl %}Daftar Peraturan | JDIH Kemenkes{% endblock %}

{% block head_bl %}
<style>
    @media (min-width:  480px) {
        .form-cari {
            position: sticky;
            top: 10px;
        }
    }
    .form-cari {
        border: 1px solid black;
        padding: 10px;
    }
</style>
{% endblock %}

{% block breadcrumb %}
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="/">
                    <span class="color-kemkes"><i class="bi bi-house-fill"></i></span>
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Peraturan</li>
        </ol>
    </nav>
</div>
{% endblock %}

{% block body_bl %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-4 col-cari">
            <form class="form-cari px-4 py-3 me-5" method="get" action="{% url 'jdih:daftar_peraturan' %}">
                <h2 class="color-kemkes" style="font-size: 1.5rem;">Pencarian</h2>
                <label class="form-label" for="keyword">Kata kunci</label>
                <input type="text" class="form-control" id="keyword" name="keyword" autofocus value="{{ keyword }}" maxlength="30">

                <label class="form-label mt-3" for="nomor">Nomor</label>
                <input name="nomor" type="number" min="1" max="9999" class="form-control" value="{{ nomor }}">

                <label class="form-label mt-3" for="tahun">Tahun</label>
                <input name="tahun" type="number" min="1900" max="2077" class="form-control" value="{{ tahun }}">

                <label class="form-label mt-3" for="bentuk">Bentuk</label>
                <select class="form-select" id="bentuk" name="bentuk">
                    <option {% if not bentuk %}selected{% endif %} value=""></option>
                    {% for bentuk_i in bentuks %}
                    <option {% if bentuk == bentuk_i.id %}selected{% endif %} value="{{ bentuk_i.id }}">{{ bentuk_i.nama_lengkap_bentuk }}</option>
                    {% endfor %}
                </select>
                {% comment %}
                <label class="form-label mt-3" for="subyek">Subyek</label>
                <select class="form-select" id="subyek" name="subyek">
                    <option selected value="0"></option>
                    {% for subyek in subyeks %}
                    <option value="{{ subyek.id }}">{{ subyek.judul }}</option>
                    {% endfor %}
                </select>

                <label class="form-label mt-3" for="kategori">Kategori</label>
                <select class="form-select" id="kategori" name="kategori">
                    <option selected value="0"></option>
                    {% for kategori in kategoris %}
                    <option value="{{ kategori.id }}">{{ kategori.judul }}</option>
                    {% endfor %}
                </select>
                {% endcomment %}

                <div class="d-grid gap-2 mt-5">
                    <button class="btn btn-dark btn-kemkes" type="submit">Cari</button>
                </div>
            </form>
        </div>
        <div class="col-md-8">
            <h1 class="color-kemkes" style="font-size: 1.5rem;">Daftar Peraturan</h1>
            {% if not peraturans %}
            Tidak ada peraturan ditemukan.
            {% endif %}
            {% for peraturan in peraturans %}
            <a style="color: black; text-decoration: none;" href="{% url 'jdih:detail' peraturan.id %}" class="m-3">
                <div class="card" style="min-height: 192px;">
                    <div class="card-body">
                        <h5 class="card-title">{{ peraturan.kode }} {% if peraturan.status != status_berlaku %}<span class="badge text-bg-secondary">{{ peraturan.get_status_display }}</span>{% endif %}</h5>
                        <p class="card-text">
                            <h6 style="font-size: large;">{{ peraturan.judul|title }}</h6>
                            {% if peraturan.headline %}
                            ... {{ peraturan.headline|safe }} ... 
                            {% endif %}
                        </p>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <div>
                            <i class="bi bi-calendar-event"></i>&nbsp;{{ peraturan.tanggal_penetapan|default:peraturan.created_at|date:"d F Y" }}
                        </div>
                        <div title="Dilihat sebanyak">
                            <i class="bi bi-eye"></i>&nbsp;{{ peraturan.jumlah_lihat }}
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}
            <nav aria-label="pagination">
                <ul class="pagination">
                    {% for p in paginator_range %}
                    <li class="page-item">
                        {% if p == peraturans.number %}
                        <span class="page-link" style="color: black;">{{ p }}</span>
                        {% else %}
                        <a class="page-link color-kemkes" href="{% if p == peraturans.number or p == '…' %}#{% else %}?{% query_transform laman=p %}{% endif %}">{{ p }}</a>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

jdih/templates/jdih/detail-peraturan.html
{% extends 'jdih/BASE.html' %}

{% block head_bl %}

{% endblock %}

{% block title_bl %}{{ peraturan.bentuk.nama_lengkap_bentuk }} {{ peraturan.kode }} | JDIH Kemenkes{% endblock %}

{% block breadcrumb %}
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="/">
                    <span class="color-kemkes"><i class="bi bi-house-fill"></i></span>
                </a>
            </li>
            <li class="breadcrumb-item"><a href="{% url 'jdih:daftar_peraturan' %}">
                    <span class="color-kemkes">Peraturan</span>
                </a></li>
            <li class="breadcrumb-item active" aria-current="page">Detail Peraturan</li>
        </ol>
    </nav>
</div>
{% endblock %}

{% block body_bl %}
<div class="container mt-5">
    <h1 class="color-kemkes">
        <span style="font-size: 1.5rem;">Detail Peraturan </span>
    </h1>
    {% if messages %}
    <div class="p-3 my-3" style="background-color: #60C0D0;">
        Anda tadi mencari kata kunci: <b>{% for m in messages %}{{ m }} {% endfor %}</b>
    </div>
    {% endif %}
    <div class="card">
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Meta</th>
                        <th>Keterangan</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Kode</td>
                        <td>{{ peraturan.kode }}</td>
                    </tr>
                    <tr>
                        <td>Judul</td>
                        <td>{{ peraturan.judul }}</td>
                    </tr>
                    <tr>
                        <td>Bentuk</td>
                        <td>{{ peraturan.bentuk }}</td>
                    </tr>
                    <tr>
                        <td>Nomor</td>
                        <td>{{ peraturan.nomor }}</td>
                    </tr>
                    <tr>
                        <td>Tahun</td>
                        <td>{{ peraturan.tahun }}</td>
                    </tr>
                    {% comment %}
                    <tr>
                        <td>Subyek</td>
                        <td>
                            {% for s in peraturan.subyek.all %}
                            <span class="badge text-bg-light">{{ s }}</span>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td>Kategori</td>
                        <td>
                            {% for k in peraturan.kategori.all %}
                            <span class="badge text-bg-light">{{ k }}</span>
                            {% endfor %}
                        </td>
                    </tr>
                    {% endcomment %}
                    <tr>
                        <td>Eselon I Pemrakarsa</td>
                        <td>{{ peraturan.unit_eselon_1_pemrakarsa|default:'-' }}</td>
                    </tr>
                    <tr>
                        <td>Tempat Penetapan</td>
                        <td>{{ peraturan.tempat_penetapan|default:'-' }}</td>
                    </tr>
                    <tr>
                        <td>Tanggal Penetapan</td>
                        <td>{{ peraturan.tanggal_penetapan|date:'d F Y'|default:'-' }}</td>
                    </tr>
                    <tr>
                        <td>Tanggal Pengundangan</td>
                        <td>{{ peraturan.tanggal_pengundangan|date:'d F Y'|default:'-' }}</td>
                    </tr>
                    <tr>
                        <td>Tanggal Berlaku Efektif</td>
                        <td>{{ peraturan.tanggal_berlaku_efektif|date:'d F Y'|default:'-' }}</td>
                    </tr>
                    <tr>
                        <td>Status</td>
                        <td>{{ peraturan.get_status_display }}</td>
                    </tr>
                    <tr>
                        <td>Riwayat</td>
                        <td>
                            <ul>
                                <li>Ditambahkan ke basis data JDIH pada {{ peraturan.created_at|date:'d F Y' }}</li>
                            <!-- UNTUK P AKTIF -->
                            {% for p in peraturan.mencabuts.all %}
                                <li>Mencabut <a href="{% url 'jdih:detail' p.id %}">{{ p.kode }}</a> {{ p.judul }}</li>
                            {% endfor %}
                            {% for p in peraturan.mencabut_sebagians.all %}
                                <li>Mencabut sebagian <a href="{% url 'jdih:detail' p.id %}">{{ p.kode }}</a> {{ p.judul }}</li>
                            {% endfor %}
                            {% for p in peraturan.mengubahs.all %}
                                <li>Mengubah <a href="{% url 'jdih:detail' p.id %}">{{ p.kode }}</a> {{ p.judul }}</li>
                            {% endfor %}
                            {% for p in peraturan.melengkapis.all %}
                                <li>Melengkapi <a href="{% url 'jdih:detail' p.id %}">{{ p.kode }}</a> {{ p.judul }}</li>
                            {% endfor %}
                            <!-- UNTUK P NON AKTIF -->
                            {% for p in peraturan.pencabuts.all %}
                                <li>Dicabut oleh <a href="{% url 'jdih:detail' p.id %}">{{ p.kode }}</a> {{ p.judul }}</li>
                            {% endfor %}
                            {% for p in peraturan.pencabut_sebagians.all %}
                                <li>Dicabut sebagian oleh <a href="{% url 'jdih:detail' p.id %}">{{ p.kode }}</a> {{ p.judul }}</li>
                            {% endfor %}
                            {% for p in peraturan.pengubahs.all %}
                                <li>Diubah oleh <a href="{% url 'jdih:detail' p.id %}">{{ p.kode }}</a> {{ p.judul }}</li>
                            {% endfor %}
                            {% for p in peraturan.pelengkaps.all %}
                                <li>Dilengkapi oleh <a href="{% url 'jdih:detail' p.id %}">{{ p.kode }}</a> {{ p.judul }}</li>
                            {% endfor %}
                            </ul>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% if dokumen_tersedia %}
    <div class="mt-5 px-auto">
        <div>
            <a class="btn btn-dark btn-kemkes btn-sm rounded-pill mb-3" href="{% url 'jdih:unduh' peraturan.id %}">
                <span class="px-3"><i class="bi bi-cloud-download"></i>&ThickSpace; Unduh dokumen</span>
            </a>
        </div>
        <object data="{% url 'jdih:unduh' peraturan.id %}" type="application/pdf" width="100%" height="1000">
            <a href="{% url 'jdih:unduh' peraturan.id %}">Unduh Dokumen</a>
        </object>
    </div>    
    {% endif %}
</div>
{% endblock %}

jdih/templates/jdih/extract-text.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ekstraksi Teks PDF</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <h1>Ekstraksi Teks PDF</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="try">
            <button type="submit">Unggah</button>
        </form>
        {% if extracted_text %}
        <div class="my-5">
            <h3>Kata Kunci</h3>
            <ol>
                {% for word, count in keywords_count %}
                <li>{{ word }} <span class="badge bg-secondary">{{ count }}</span></li>
                {% endfor %}
            </ol>
            <h3 class="mt-5">Teks terbaca</h3>
            <code>
                {{ extracted_text }}
            </code>
        </div>
        {% endif %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
        crossorigin="anonymous"></script>
</body>

</html>